datasource_mode = "Db"

[filters.pubkey]
enabled = true
filter_mode = "Whitelist"

[filters.kind]
enabled = true
filter_mode = "Blacklist"

[filters.rate_limit]
enabled = false
max_events = 10
time_window = 60 # in seconds

[filters.content]
enabled = false
validated_kinds = [1] # Choose which kinds you want to validate the content field for

[database]
host = "localhost"
port = "5432"
user = "chief"
password = "changeme"
dbname = "chief"

[json]
file_path = ""